### ISSUE TITLE
VirtualPath IFileProvider DI

### ISSUE THREAD

**Issue by erfan-kamali-azihub** [CoreWebForms/CoreWebForms#255]
I brought BuildManager class and some VirtualPath methods need IFileProvider. How can I access the default provider from DI or something else to pass it?

**Comment by twsouthwick** [comment]
For now, if it's expected to be within a request, use HttpContext.Current and if it could be outside of a request, use `HttpRuntimeHelper.Services`.

We don't really want BuildManager as is - if you want to enable a few of the APIs, that's fine, but otherwise it should be gutted. We've redone the compilation system and BuildManager was the entry to that.

**Comment by erfan-kamali-azihub** [comment]
Thank you, I'm gonna close this.
